version: "3.9"

services:
  ddns:
    container_name: ddns
    image: linuxserver/ddclient:latest # https://hub.docker.com/r/linuxserver/ddclient
    networks:
      vpn:
        ipv4_address: 10.1.0.11
    environment:
      PUID: 1001
      PGID: 1001
      TZ: America/New_York
    volumes:
      - ./ddclient.conf:/config/ddclient.conf
    restart: unless-stopped

  certbot:
    container_name: certbot
    image: certbot/certbot # https://hub.docker.com/r/certbot/certbot
    depends_on:
      - ddns
    networks:
      vpn:
        ipv4_address: 10.1.0.12
    ports:
      - 80:80/tcp
    volumes:
      - ./certbot-etc-letsencrypt/:/etc/letsencrypt/
      - ./certbot-var-lib-letsencrypt/:/var/lib/letsencrypt/
      - ./certbot-var-www-letsencrypt/:/var/www/letsencrypt/
    restart: on-failure:2
    command: certonly --standalone --non-interactive --preferred-challenges http --agree-tos --email EMAIL!!! -d DDNS!!!

  wireguard:
    container_name: wg
    image: linuxserver/wireguard:latest # https://hub.docker.com/r/linuxserver/wireguard
    depends_on:
      - ddns
      - pihole
    networks:
      vpn:
        ipv4_address: 10.1.0.2
    ports:
      - 51820:51820/udp
    dns: 10.1.0.3
    environment:
      PUID: 1001
      PGID: 1001
      TZ: America/New_York
      PEERS: PEERS!!!
      INTERNAL_SUBNET: 10.1.1.0
      SERVERURL: DDNS!!!
      SERVERPORT: 51820
      ALLOWEDIPS: 10.1.0.0/16
    volumes:
      - ./wireguard-config/:/config/
      - ./wireguard-lib-modules/:/lib/modules/
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
  
  pihole:
    # https://github.com/pi-hole/docker-pi-hole
    container_name: pihole
    image: pihole/pihole:latest # https://hub.docker.com/r/pihole/pihole
    depends_on:
      - unbound
    networks:
      vpn:
        ipv4_address: 10.1.0.3
    dns: 127.0.0.1
    extra_hosts: 
      - local:10.1.0.1
    environment:
      TZ: America/New_York
      FTLCONF_LOCAL_IPV4: 10.1.0.3
      PIHOLE_DNS_: 10.1.0.4
      DNSSEC: 'true'
      REV_SERVER: 'true'
      REV_SERVER_TARGET: 10.1.0.1
      REV_SERVER_CIDR: 10.1.0.0/16
      ADMIN_EMAIL: EMAIL!!!
      WEBPASSWORD: PIPASS!!!
    volumes:
       - ./pihole-etc-pihole/:/etc/pihole/
       - ./pihole-etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  unbound:
    # https://docs.pi-hole.net/guides/dns/unbound/
    container_name: unbound
    image: klutchell/unbound:latest # https://hub.docker.com/r/klutchell/unbound
    networks:
      vpn:
        ipv4_address: 10.1.0.4
    environment:
      TZ: America/New_York
    volumes:
      - ./unbound-etc-unbound-custom.conf.d/:/etc/unbound/custom.conf.d/
      - ./unbound-var-log-unbound/:/var/log/unbound/
      - ./unbound.conf:/etc/unbound/custom.conf.d/unbound.conf
    restart: unless-stopped

  dnsproxy:
    container_name: proxy
    image: chenhw2/dnsproxy:latest # https://hub.docker.com/r/chenhw2/dnsproxy
    depends_on:
      - ddns
      - certbot
      - pihole
    networks:
      vpn:
        ipv4_address: 10.1.0.5
    ports:
      - 443:443/tcp # DNS-over-HTTPS
      - 853:853/tcp # DNS-over-TLS
      - 853:853/udp
      - 1853:1853/tcp # DNS-over-QUIC
      - 1853:1853/udp
      - 2853:2853/tcp # DNSCrypt
      - 2853:2853/udp
    volumes:
      - ./certbot-etc-letsencrypt/:/etc/letsencrypt/
    restart: unless-stopped
    command: dnsproxy -l=0.0.0.0 -s=443 -t=853 -q=1853 -y=2853 -u=10.1.0.3 -f=1.1.1.1 -r=20 -c=/etc/letsencrypt/live/DDNS!!!/fullchain.pem -k=/etc/letsencrypt/live/DDNS!!!/privkey.pem --fastest-addr --refuse-any --udp-buf-size=1024

networks:
  vpn:
    name: vpn
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
          gateway: 10.1.0.1
          